### ISSUE TITLE
CPU percentage is wrong with about factor 10

### ISSUE THREAD

**Issue by marcelwolf1989** [sebhildebrandt/dockerstats#1]
### Issue Type

* [X ] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- The percentage of cpu_percent should match the docker stats percentage  of cpu usage

### Actual behavior

- It is about factor 10 wrong
- 
- 

### Steps to reproduce the problem

- Open docker stats and parallel call the percentage with dockerstats
-
-

### Specifications 

- package version: 1.1.0
- docker version: 17.12.0-ce, build c97c6d6
- operating system: Ubuntu 16.04 LTS
- hardware:

### Problem and possible solution

Docker stats calculate the stats with this : https://github.com/docker/docker/blob/eb131c5383db8cac633919f82abad86c99bffbe5/cli/command/container/stats_helpers.go#L175

**Comment by sebhildebrandt** [comment]
Thank you. Will have a look on it later this week, ok?

**Comment by marcelwolf1989** [comment]
Hey @sebhildebrandt can you reproduce this issue?

**Comment by sebhildebrandt** [comment]
@marcelwolf1989 Sorry about my late reply!!! I had quite a lot of work for the `systeminformation` npm module (adding FreeBSD support) so I didn't yet had a look on this issue. Anyway I plan to focus on this this weekend. Sorry once again.

**Comment by marcelwolf1989** [comment]
No Problem! Thank you for providing this easy to use dockerstats tool!

**Comment by sebhildebrandt** [comment]
Still investigating ... just want to sure that I really understand what is going on ... ;-)
Thank you for your patience ...

**Comment by marcelwolf1989** [comment]
hey @sebhildebrandt is there something new for this issue? Could you reproduce this ?

**Comment by marcelwolf1989** [comment]
hey @sebhildebrandt is there something new for this issue?

**Comment by sebhildebrandt** [comment]
Just published a fix for that (v 1.2.4) ... sorry for the delay ...
