### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by daaru00** [sebhildebrandt/dockerstats#2]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Actual behavior

Return an error:
```
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at Socket.socket.on (/app/node_modules/dockerstats/lib/dockerSocket.js:42:23)
at emitNone (events.js:111:20)
at Socket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

### Steps to reproduce the problem

- Retrive stats with a large number of containers

### Specifications 

- package version: 1.1.0
- node version: v8.11.3
- docker version: 17.12.0-ce, build c97c6d6
- operating system: Linux c73d22936e9d 4.9.75-moby
- hardware: Docker

### Problem and possible solution

I noticed that on [this raw](https://github.com/sebhildebrandt/dockerstats/blob/master/lib/dockerSocket.js#L40) you cut the string with substring at char 100000, I think my stats is bigger. The JSON input indicated ends with:
```
...State":"running","Status":"Up Less than a second","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"metric-colletor_default":{"IPAMConfig":{"IPv4Address":
```
it seems truncated, I suppose this can be the issue cause. This problems happen in a Swarm worker with an average of 72 containers, doing `docker ps --format '{{ json . }}'` from terminal I correctly see a non-trucated json, counting characters the result is:
```
~ $ docker ps --format '{{ json . }}' | wc -m
55463
```

Is it possible to increment it or better add an option to override or disable it?

**Comment by sebhildebrandt** [comment]
I published some changes (not only substring size) that solves also this issue. Version 1.2.2 just published
