### ISSUE TITLE
Docker stats monitor from container

### ISSUE THREAD

**Issue by PixellUp** [sebhildebrandt/dockerstats#5]
### Issue Type

* [ ] Bug
* [ ] Feature Request
* [X] Question

### Expected behavior 

I'm looking for a way to containerize the node js docker stats single index.js app into own image and be used as a drop in image for host instead of having to install node.js on the host and managing the auto-restart / crash-proof of the index.js. Unfortunately, the docker container with node js image and the script doesn't pick any containers outside own container making it unfunctional. 
I've tried pointing the docker socket path to the container path but also failed to display any information.

### Actual behavior

-  Display containers information from the container itself

### Steps to reproduce the problem

```
FROM node:10
WORKDIR /app
COPY package.json /app
COPY yarn.lock /app
RUN yarn
COPY . /app
CMD node index.js
EXPOSE 3000
```

### Specifications 

- package version: 1.2.8
- docker version: 18.09.1, build 4c52b90
- operating system: MacOS High Sierra

**Comment by sebhildebrandt** [comment]
@PixellUp ... need to test it here ... didn't tried to do that. I will come back to you if I managed to solve this, OK?

**Comment by PixellUp** [comment]
@sebhildebrandt Aye, any luck? I've uploaded my test files in case that helps https://gist.github.com/PixellUp/12e3fe08f73dfc96ad9b76cbb6d05779

**Comment by sebhildebrandt** [comment]
Not yet ... working hard on finalising a new major version or one of my other packages (systeminformation) ... will take some time ...

**Comment by tdurieux** [comment]
I am also interested in this @sebhildebrandt do you have news?
