### ISSUE TITLE
DockerContainerStatsData.netIO.wx always undefined or 0

### ISSUE THREAD

**Issue by toolcreator** [sebhildebrandt/dockerstats#7]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- `DockerContainerStatsData.netIO.wx` contains number of transmitted bytes

### Actual behavior

- `DockerContainerStatsData.netIO.wx` is always `undefined` or `0`
- `DockerContainerStatsData.netIO.tx` contains number of transmitted bytes (or is `undefined` or `0`)

### Steps to reproduce the problem

1. Use `dockerContainerStats` to retrieve `DockerContainerStatsData`
2. Try to access `DockerContainerStatsData.netIO.wx` - it's always `undefined` or `0`

### Specifications 

- package version: 1.4.3
- docker version: Docker version 19.03.13-ce, build 4484c46d9d
- operating system: Linux 5.4.80-2-MANJARO
- hardware: Irrelevant

### Problem and possible solution

Rename `tx` to `wx` in the returned object in *docker.js* line 295 (PR incoming).

**Comment by sebhildebrandt** [comment]
@toolcreator Fixed. Sorry!! Version 1.4.4. just published.

**Comment by toolcreator** [comment]
@sebhildebrandt Thanks a lot for the quick reply and fix!
Btw, if you're interested, [this](https://github.com/toolcreator/dstatsd) is the project I'm using the library in.
